export const cityStates = [
  {
    "stateId": 1, "state": "Alabama", "cities": [
      { "city": "Alexander City" },
      { "city": "Andalusia" },
      { "city": "Athens" },
      { "city": "Atmore" },
      { "city": "Auburn" },
      { "city": "Bessemer" },
      { "city": "Birmingham" },
      { "city": "Chickasaw" },
      { "city": "Clanton" },
      { "city": "Cullman" },
      { "city": "Decatur" },
      { "city": "Demopolis" },
      { "city": "Dothan" },
      { "city": "Enterprise" },
      { "city": "Eufaula" },
      { "city": "Florence" },
      { "city": "Fort Payne" },
      { "city": "Gadsden" },
      { "city": "Greenville" },
      { "city": "Guntersville" },
      { "city": "Huntsville" },
      { "city": "Jasper" },
      { "city": "Marion" },
      { "city": "Mobile" },
      { "city": "Montgomery" },
      { "city": "Opelika" },
      { "city": "Ozark" },
      { "city": "Phenix City" },
      { "city": "Prichard" },
      { "city": "Scottsboro" },
      { "city": "Selma" },
      { "city": "Sheffield" },
      { "city": "Sylacauga" },
      { "city": "Talladega" },
      { "city": "Prichard" },
      { "city": "Troy" },
      { "city": "Tuscaloosa" },
      { "city": "Tuscumbia" },
      { "city": "Tuskegee" }
    ]
  },
  {
    "stateId": 2, "state": "Alaska", "cities": [
      { "city": "Anchorage" },
      { "city": "Cordova" },
      { "city": "Fairbanks" },
      { "city": "Haines" },
      { "city": "Homer" },
      { "city": "Juneau" },
      { "city": "Ketchikan" },
      { "city": "Kodiak" },
      { "city": "Kotzebue" },
      { "city": "Nome" },
      { "city": "Palmer" },
      { "city": "Seward" },
      { "city": "Sitka" },
      { "city": "Skagway" },
      { "city": "Valdez" },
    ]
  },
  {
    "stateId": 3, "state": "Arizona", "cities": [
      { "city": "Ajo" },
      { "city": "Avondale" },
      { "city": "Bisbee" },
      { "city": "Casa Grande" },
      { "city": "Chandler" },
      { "city": "Clifton" },
      { "city": "Douglas" },
      { "city": "Flagstaff" },
      { "city": "Florence" },
      { "city": "Gila Bend" },
      { "city": "Glendale" },
      { "city": "Globe" },
      { "city": "Kingman" },
      { "city": "Lake Havasu City" },
      { "city": "Mesa" },
      { "city": "Nogales" },
      { "city": "Oraibi" },
      { "city": "Phoenix" },
      { "city": "Prescott" },
      { "city": "Scottsdale" },
      { "city": "Sierra Vista" },
      { "city": "Tempe" },
      { "city": "Tombstone" },
      { "city": "Tucson" },
      { "city": "Walpi" },
      { "city": "Window Rock" },
      { "city": "Winslow" },
      { "city": "Yuma" },
    ]
  },
  {
    "stateId": 4, "state": "Arkansas", "cities": [
      { "city": "Arkadelphia" },
      { "city": "Arkansas Post" },
      { "city": "Batesville" },
      { "city": "Benton" },
      { "city": "Blytheville" },
      { "city": "Camden" },
      { "city": "Conway" },
      { "city": "Crossett" },
      { "city": "El Dorado" },
      { "city": "Fayetteville" },
      { "city": "Forrest City" },
      { "city": "Fort Smith" },
      { "city": "Harrison" },
      { "city": "Helena" },
      { "city": "Hope" },
      { "city": "Hot Springs" },
      { "city": "Jacksonville" },
      { "city": "Jonesboro" },
      { "city": "Little Rock" },
      { "city": "Magnolia" },
      { "city": "Morrilton" },
      { "city": "Newport" },
      { "city": "North Little Rock" },
      { "city": "Osceola" },
      { "city": "Pine Bluff" },
      { "city": "Rogers" },
      { "city": "Searcy" },
      { "city": "Stuttgart" },
      { "city": "Van Buren" },
      { "city": "West Memphis" },
    ]
  },
  // {
  //   "stateId": 4, "state": "Arkansas", "cities": [
  //     { "city": "Arkadelphia" },
  //     { "city": "Arkansas Post" },
  //     { "city": "Batesville" },
  //     { "city": "Benton" },
  //     { "city": "Blytheville" },
  //     { "city": "Camden" },
  //     { "city": "Conway" },
  //     { "city": "Crossett" },
  //     { "city": "El Dorado" },
  //     { "city": "Fayetteville" },
  //     { "city": "Forrest City" },
  //     { "city": "Fort Smith" },
  //     { "city": "Harrison" },
  //     { "city": "Helena" },
  //     { "city": "Hope" },
  //     { "city": "Hot Springs" },
  //     { "city": "Jacksonville" },
  //     { "city": "Jonesboro" },
  //     { "city": "Little Rock" },
  //     { "city": "Magnolia" },
  //     { "city": "Morrilton" },
  //     { "city": "Newport" },
  //     { "city": "North Little Rock" },
  //     { "city": "Osceola" },
  //     { "city": "Pine Bluff" },
  //     { "city": "Rogers" },
  //     { "city": "Searcy" },
  //     { "city": "Stuttgart" },
  //     { "city": "Van Buren" },
  //     { "city": "West Memphis" },
  //   ]
  // },
  {
    "stateId": 5, "state": "California", "cities": [
      { "city": "Alameda" },
      { "city": "Alhambra" },
      { "city": "Anaheim" },
      { "city": "Antioch" },
      { "city": "Arcadia" },
      { "city": "Bakersfield" },
      { "city": "Barstow" },
      { "city": "Belmont" },
      { "city": "Berkeley" },
      { "city": "Beverly Hills" },
      { "city": "Brea" },
      { "city": "Buena Park" },
      { "city": "Burbank" },
      { "city": "Calexico" },
      { "city": "Calistoga" },
      { "city": "Carlsbad" },
      { "city": "Carmel" },
      { "city": "Chico" },
      { "city": "Chula Vista" },
      { "city": "Claremont" },
      { "city": "Compton" },
      { "city": "Concord" },
      { "city": "Corona" },
      { "city": "Coronado" },
      { "city": "Costa Mesa" },
      { "city": "Culver City" },
      { "city": "Daly City" },
      { "city": "Davis" },
      { "city": "Downey" },
      { "city": "El Centro" },
      { "city": "El Cerrito" },
      { "city": "El Monte" },
      { "city": "Escondido" },
      { "city": "Eureka" },
      { "city": "Fairfield" },
      { "city": "Fontana" },
      { "city": "Fremont" },
      { "city": "Fresno" },
      { "city": "Fullerton" },
      { "city": "Garden Grove" },
      { "city": "Glendale" },
      { "city": "Hayward" },
      { "city": "Hollywood" },
      { "city": "Huntington Beach" },
      { "city": "Indio" },
      { "city": "Inglewood" },
      { "city": "Irvine" },
      { "city": "La Habra" },
      { "city": "Laguna Beach" },
      { "city": "Lancaster" },
      { "city": "Livermore" },
      { "city": "Lodi" },
      { "city": "Lompoc" },
      { "city": "Long Beach" },
      { "city": "Los Angeles" },
      { "city": "Malibu" },
      { "city": "Martinez" },
      { "city": "Marysville" },
      { "city": "Menlo Park" },
      { "city": "Merced" },
      { "city": "Modesto" },
      { "city": "Monterey" },
      { "city": "Mountain View" },
      { "city": "Napa" },
      { "city": "Needles" },
      { "city": "Newport Beach" },
      { "city": "Norwalk" },
      { "city": "Novato" },
      { "city": "Oakland" },
      { "city": "Oceanside" },
      { "city": "Ojai" },
      { "city": "Ontario" },
      { "city": "Orange" },
      { "city": "Oroville" },
      { "city": "Oxnard" },
      { "city": "Pacific Grove" },
      { "city": "Palm Springs" },
      { "city": "Palmdale" },
      { "city": "Palo Alto" },
      { "city": "Pasaden" },
      { "city": "Petaluma" },
      { "city": "Pomona" },
      { "city": "Port Hueneme" },
      { "city": "Rancho Cucamonga" },
      { "city": "Red Bluff" },
      { "city": "Redding" },
      { "city": "Redlands" },
      { "city": "Redondo Beach" },
      { "city": "Redwood City" },
      { "city": "Richmond" },
      { "city": "Riverside" },
      { "city": "Roseville" },
      { "city": "Sacramento" },
      { "city": "Salinas" },
      { "city": "San Bernardino" },
      { "city": "San Clemente" },
      { "city": "San Diego" },
      { "city": "San Fernando" },
      { "city": "San Francisco" },
      { "city": "San Gabriel" },
      { "city": "San Jose" },
      { "city": "San Juan Capistrano" },
      { "city": "San Leandro" },
      { "city": "San Luis Obispo" },
      { "city": "San Marino" },
      { "city": "San Mateo" },
      { "city": "San Pedro" },
      { "city": "San Rafael" },
      { "city": "San Simeon" },
      { "city": "Santa Ana" },
      { "city": "Santa Barbara" },
      { "city": "Santa Clara" },
      { "city": "Santa Clarita" },
      { "city": "Santa Cruz" },
      { "city": "Santa Monica" },
      { "city": "Santa Rosa" },
      { "city": "Sausalito" },
      { "city": "Simi Valley" },
      { "city": "Sonoma" },
      { "city": "South San Francisco" },
      { "city": "Stockton" },
      { "city": "Sunnyvale" },
      { "city": "Susanville" },
      { "city": "Thousand Oaks" },
      { "city": "Torrance" },
      { "city": "Turlock" },
      { "city": "Ukiah" },
      { "city": "Vallejo" },
      { "city": "Ventura" },
      { "city": "Victorville" },
      { "city": "Visalia" },
      { "city": "Walnut Creek" },
      { "city": "Watts" },
      { "city": "West Covina" },
      { "city": "Whittier" },
      { "city": "Woodland" },
      { "city": "Yorba Linda" },
      { "city": "Yuba City" },
    ]
  },
  {
    "stateId": 6, "state": "Colorado", "cities": [
      { "city": "Alamosa" },
      { "city": "Aspen" },
      { "city": "Aurora" },
      { "city": "Boulder" },
      { "city": "Breckenridge" },
      { "city": "Brighton" },
      { "city": "Canon City" },
      { "city": "Central City" },
      { "city": "Climax" },
      { "city": "Colorado Springs" },
      { "city": "Cortez" },
      { "city": "Cripple Creek" },
      { "city": "Denver" },
      { "city": "Durango" },
      { "city": "Englewood" },
      { "city": "Estes Park" },
      { "city": "Fort Collins" },
      { "city": "Fort Morgan" },
      { "city": "Georgetown" },
      { "city": "Glenwood Springs" },
      { "city": "Golden" },
      { "city": "Grand Junction" },
      { "city": "Greeley" },
      { "city": "Gunnison" },
      { "city": "La Junta" },
      { "city": "Leadville" },
      { "city": "Littleton" },
      { "city": "Longmont" },
      { "city": "Loveland" },
      { "city": "Montrose" },
      { "city": "Ouray" },
      { "city": "Pagosa Springs" },
      { "city": "Pueblo" },
      { "city": "Silverton" },
      { "city": "Steamboat Springs" },
      { "city": "Sterling" },
      { "city": "Telluride" },
      { "city": "Trinidad" },
      { "city": "Vail" },
      { "city": "Walsenburg" },
      { "city": "Westminster" }
    ]
  },
  {
    "stateId": 7, "state": "Connecticut", "cities": [
      { "city": "Ansonia" },
      { "city": "Berlin" },
      { "city": "Bloomfield" },
      { "city": "Branford" },
      { "city": "Bridgeport" },
      { "city": "Bristol" },
      { "city": "Coventry" },
      { "city": "Danbury" },
      { "city": "Darien" },
      { "city": "Derby" },
      { "city": "East Hartford" },
      { "city": "East Haven" },
      { "city": "Enfield" },
      { "city": "Fairfield" },
      { "city": "Farmington" },
      { "city": "Greenwich" },
      { "city": "Groton" },
      { "city": "Guilford" },
      { "city": "Hamden" },
      { "city": "Hartford" },
      { "city": "Lebanon" },
      { "city": "Litchfield" },
      { "city": "Manchester" },
      { "city": "Mansfield" },
      { "city": "Meriden" },
      { "city": "Middletown" },
      { "city": "Milford" },
      { "city": "Mystic" },
      { "city": "Naugatuck" },
      { "city": "New Britain" },
      { "city": "New Haven" },
      { "city": "New London" },
      { "city": "North Haven" },
      { "city": "Norwalk" },
      { "city": "Norwich" },
      { "city": "Old Saybrook" },
      { "city": "Orange" },
      { "city": "Seymour" },
      { "city": "Shelton" },
      { "city": "Simsbury" },
      { "city": "Southington" },
      { "city": "Stamford" },
      { "city": "Stonington" },
      { "city": "Stratford" }, ,
      { "city": "Torrington" },
      { "city": "Wallingford" },
      { "city": "Waterbury" },
      { "city": "Waterford" },
      { "city": "Watertown" },
      { "city": "West Hartford" },
      { "city": "West Haven" },
      { "city": "Westport" },
      { "city": "Wethersfield" },
      { "city": "Willimantic" },
      { "city": "Windham" },
      { "city": "Windsor" },
      { "city": "Windsor Locks" },
      { "city": "Winsted" },
    ]
  },
  {
    "stateId": 8, "state": "Delaware", "cities": [
      { "city": "Dover" },
      { "city": "Lewes" },
      { "city": "Milford" },
      { "city": "New Castle" },
      { "city": "Newark" },
      { "city": "Smyrna" },
      { "city": "Wilmington" },
    ]
  },
  {
    "stateId": 9, "state": "Florida", "cities": [
      { "city": "Apalachicola" },
      { "city": "Bartow" },
      { "city": "Belle Glade" },
      { "city": "Boca Raton" },
      { "city": "Bradenton" },
      { "city": "Cape Coral" },
      { "city": "Clearwater" },
      { "city": "Cocoa Beach" },
      { "city": "Cocoa-Rockledge" },
      { "city": "Coral Gables" },
      { "city": "Daytona Beach" },
      { "city": "De Land" },
      { "city": "Deerfield Beach" },
      { "city": "Delray Beach" },
      { "city": "Fernandina Beach" },
      { "city": "Fort Lauderdale" },
      { "city": "Fort Myers" },
      { "city": "Fort Pierce" },
      { "city": "Fort Walton Beach" },
      { "city": "Gainesville" },
      { "city": "Hallandale Beach" },
      { "city": "Hialeah" },
      { "city": "Hollywood" },
      { "city": "Homestead" },
      { "city": "Jacksonville" },
      { "city": "Key West" },
      { "city": "Lake City" },
      { "city": "Lake Wales" },
      { "city": "Lakeland" },
      { "city": "Largo" },
      { "city": "Melbourne" },
      { "city": "Miami" },
      { "city": "Miami Beach" },
      { "city": "Naples" },
      { "city": "New Smyrna Beach" },
      { "city": "Ocala" },
      { "city": "Orlando" },
      { "city": "Ormond Beach" },
      { "city": "Palatka" },
      { "city": "Palm Bay" },
      { "city": "Palm Beach" },
      { "city": "Panama City" },
      { "city": "Pensacola" },
      { "city": "Pompano Beach" },
      { "city": "Saint Augustine" },
      { "city": "Saint Petersburg" },
      { "city": "Sanford" },
      { "city": "Sarasota" },
      { "city": "Sebring" },
      { "city": "Tallahassee" },
      { "city": "Tampa" },
      { "city": "Tarpon Springs" },
      { "city": "Titusville" },
      { "city": "Venice" },
      { "city": "West Palm Beach" },
      { "city": "White Springs" },
      { "city": "Winter Haven" },
      { "city": "Winter Park" },
    ]
  },
  {
    "stateId": 10, "state": "Georgia", "cities": [
      { "city": "Albany" },
      { "city": "Americus" },
      { "city": "Andersonville" },
      { "city": "Athens" },
      { "city": "Atlanta" },
      { "city": "Augusta" },
      { "city": "Bainbridge" },
      { "city": "Blairsville" },
      { "city": "Brunswick" },
      { "city": "Calhoun" },
      { "city": "Carrollton" },
      { "city": "Columbus" },
      { "city": "Dahlonega" },
      { "city": "Dalton" },
      { "city": "Darien" },
      { "city": "Decatur" },
      { "city": "Douglas" },
      { "city": "East Point" },
      { "city": "Fitzgerald" },
      { "city": "Fort Valley" },
      { "city": "Gainesville" },
      { "city": "La Grange" },
      { "city": "Macon" },
      { "city": "Marietta" },
      { "city": "Milledgeville" },
      { "city": "Plains" },
      { "city": "Rome" },
      { "city": "Savannah" },
      { "city": "Toccoa" },
      { "city": "Valdosta" },
      { "city": "Warm Springs" },
      { "city": "Warner Robins" },
      { "city": "Washington" },
      { "city": "Waycross" },
    ]
  },
  {
    "stateId": 11, "state": "Hawaii", "cities": [
      { "city": "Hanalei" },
      { "city": "Hilo" },
      { "city": "Honaunau" },
      { "city": "Honolulu" },
      { "city": "Kahului" },
      { "city": "Kaneohe" },
      { "city": "Kapaa" },
      { "city": "Kawaihae" },
      { "city": "Lahaina" },
      { "city": "Laie" },
      { "city": "Wahiawa" },
      { "city": "Wailuku" },
      { "city": "Waimea" },
    ]
  },
  {
    "stateId": 12, "state": "Idaho", "cities": [
      { "city": "Blackfoot" },
      { "city": "Boise" },
      { "city": "Bonners Ferry" },
      { "city": "Caldwell" },
      { "city": "Coeur d’Alene" },
      { "city": "Idaho City" },
      { "city": "Idaho Falls" },
      { "city": "Kellogg" },
      { "city": "Lewiston" },
      { "city": "Moscow" },
      { "city": "Nampa" },
      { "city": "Pocatello" },
      { "city": "Priest River" },
      { "city": "Rexburg" },
      { "city": "Sun Valley" },
      { "city": "Twin Falls" },
    ]
  },
  {
    "stateId": 13, "state": "Illinois", "cities": [
      { "city": "Alton" },
      { "city": "Arlington Heights" },
      { "city": "Arthur" },
      { "city": "Aurora" },
      { "city": "Belleville" },
      { "city": "Belvidere" },
      { "city": "Bloomington" },
      { "city": "Brookfield" },
      { "city": "Cahokia" },
      { "city": "Cairo" },
      { "city": "Calumet City" },
      { "city": "Canton" },
      { "city": "Carbondale" },
      { "city": "Carlinville" },
      { "city": "Carthage" },
      { "city": "Centralia" },
      { "city": "Champaign" },
      { "city": "Charleston" },
      { "city": "Chester" },
      { "city": "Chicago" },
      { "city": "Chicago Heights" },
      { "city": "Cicero" },
      { "city": "Collinsville" },
      { "city": "Danville" },
      { "city": "Decatur" },
      { "city": "DeKalb" },
      { "city": "Des Plaines" },
      { "city": "Dixon" },
      { "city": "East Moline" },
      { "city": "East Saint Louis" },
      { "city": "Effingham" },
      { "city": "Elgin" },
      { "city": "Elmhurst" },
      { "city": "Evanston" },
      { "city": "Freeport" },
      { "city": "Galena" },
      { "city": "Galesburg" },
      { "city": "Glen Ellyn" },
      { "city": "Glenview" },
      { "city": "Granite City" },
      { "city": "Harrisburg" },
      { "city": "Herrin" },
      { "city": "Highland Park" },
      { "city": "Jacksonville" },
      { "city": "Joliet" },
      { "city": "Kankakee" },
      { "city": "Kaskaskia" },
      { "city": "Kewanee" },
      { "city": "La Salle" },
      { "city": "Lake Forest" },
      { "city": "Libertyville" },
      { "city": "Lincoln" },
      { "city": "Lisle" },
      { "city": "Lombard" },
      { "city": "Macomb" },
      { "city": "Mattoon" },
      { "city": "Moline" },
      { "city": "Monmouth" },
      { "city": "Mount Vernon" },
      { "city": "Mundelein" },
      { "city": "Naperville" },
      { "city": "Nauvoo" },
      { "city": "Normal" },
      { "city": "North Chicago" },
      { "city": "Oak Park" },
      { "city": "Oregon" },
      { "city": "Ottawa" },
      { "city": "Palatine" },
      { "city": "Park Forest" },
      { "city": "Park Ridge" },
      { "city": "Pekin" },
      { "city": "Peoria" },
      { "city": "Petersburg" },
      { "city": "Pontiac" },
      { "city": "Quincy" },
      { "city": "Rantoul" },
      { "city": "River Forest" },
      { "city": "Rock Island" },
      { "city": "Rockford" },
      { "city": "Salem" },
      { "city": "Shawneetown" },
      { "city": "Skokie" },
      { "city": "South Holland" },
      { "city": "Springfield" },
      { "city": "Streator" },
      { "city": "Summit" },
      { "city": "Urbana" },
      { "city": "Vandalia" },
      { "city": "Virden" },
      { "city": "Waukegan" },
      { "city": "Wheaton" },
      { "city": "Wilmette" },
      { "city": "Winnetka" },
      { "city": "Wood River" },
      { "city": "Zion" },
    ]
  },
  {
    "stateId": 14, "state": "Indiana", "cities": [
      { "city": "Anderson" },
      { "city": "Bedford" },
      { "city": "Bloomington" },
      { "city": "Columbus" },
      { "city": "Connersville" },
      { "city": "Corydon" },
      { "city": "Crawfordsville" },
      { "city": "East Chicago" },
      { "city": "Elkhart" },
      { "city": "Elwood" },
      { "city": "Evansville" },
      { "city": "Fort Wayne" },
      { "city": "French Lick" },
      { "city": "Gary" },
      { "city": "Geneva" },
      { "city": "Goshen" },
      { "city": "Greenfield" },
      { "city": "Hammond" },
      { "city": "Hobart" },
      { "city": "Huntington" },
      { "city": "Indianapolis" },
      { "city": "Jeffersonville" },
      { "city": "Kokomo" },
      { "city": "Lafayette" },
      { "city": "Madison" },
      { "city": "Marion" },
      { "city": "Michigan City" },
      { "city": "Mishawaka" },
      { "city": "Muncie" },
      { "city": "Nappanee" },
      { "city": "Nashville" },
      { "city": "New Albany" },
      { "city": "New Castle" },
      { "city": "New Harmony" },
      { "city": "Peru" },
      { "city": "Plymouth" },
      { "city": "Richmond" },
      { "city": "Santa Claus" },
      { "city": "Shelbyville" },
      { "city": "South Bend" },
      { "city": "Terre Haute" },
      { "city": "Valparaiso" },
      { "city": "Vincennes" },
      { "city": "Wabash" },
      { "city": "West Lafayette" },
    ]
  },
  {
    "stateId": 15, "state": "Iowa", "cities": [
      { "city": "Amana Colonies" },
      { "city": "Ames" },
      { "city": "Boone" },
      { "city": "Burlington" },
      { "city": "Cedar Falls" },
      { "city": "Cedar Rapids" },
      { "city": "Charles City" },
      { "city": "Cherokee" },
      { "city": "Clinton" },
      { "city": "Council Bluffs" },
      { "city": "Davenport" },
      { "city": "Des Moines" },
      { "city": "Dubuque" },
      { "city": "Estherville" },
      { "city": "Fairfield" },
      { "city": "Fort Dodge" },
      { "city": "Grinnell" },
      { "city": "Indianola" },
      { "city": "Iowa City" },
      { "city": "Keokuk" },
      { "city": "Mason City" },
      { "city": "Mount Pleasant" },
      { "city": "Muscatine" },
      { "city": "Newton" },
      { "city": "Oskaloosa" },
      { "city": "Ottumwa" },
      { "city": "Sioux City" },
      { "city": "Waterloo" },
      { "city": "Webster City" },
      { "city": "West Des Moines" },
    ]
  },
  {
    "stateId": 16, "state": "Kansas", "cities": [
      { "city": "Abilene" },
      { "city": "Arkansas City" },
      { "city": "Atchison" },
      { "city": "Chanute" },
      { "city": "Coffeyville" },
      { "city": "Council Grove" },
      { "city": "Dodge City" },
      { "city": "Emporia" },
      { "city": "Fort Scott" },
      { "city": "Garden City" },
      { "city": "Great Bend" },
      { "city": "Hays" },
      { "city": "Hutchinson" },
      { "city": "Independence" },
      { "city": "Junction City" },
      { "city": "Kansas City" },
      { "city": "Lawrence" },
      { "city": "Leavenworth" },
      { "city": "Liberal" },
      { "city": "Manhattan" },
      { "city": "McPherson" },
      { "city": "Medicine Lodge" },
      { "city": "Newton" },
      { "city": "Olathe" },
      { "city": "Osawatomie" },
      { "city": "Ottawa" },
      { "city": "Overland Park" },
      { "city": "Pittsburg" },
      { "city": "Salina" },
      { "city": "Shawnee" },
      { "city": "Smith Center" },
      { "city": "Topeka" },
      { "city": "Wichita" },

    ]
  },
  {
    "stateId": 17, "state": "Kentucky", "cities": [
      { "city": "Ashland" },
      { "city": "Barbourville" },
      { "city": "Bardstown" },
      { "city": "Berea" },
      { "city": "Boonesborough" },
      { "city": "Bowling Green" },
      { "city": "Campbellsville" },
      { "city": "Covington" },
      { "city": "Danville" },
      { "city": "Elizabethtown" },
      { "city": "Frankfort" },
      { "city": "Harlan" },
      { "city": "Harrodsburg" },
      { "city": "Hazard" },
      { "city": "Henderson" },
      { "city": "Hodgenville" },
      { "city": "Hopkinsville" },
      { "city": "Lexington" },
      { "city": "Louisville" },
      { "city": "Mayfield" },
      { "city": "Maysville" },
      { "city": "Middlesboro" },
      { "city": "Newport" },
      { "city": "Owensboro" },
      { "city": "Paducah" },
      { "city": "Paris" },
      { "city": "Richmond" },
    ]
  },
  {
    "stateId": 18, "state": "Louisiana", "cities": [
      { "city": "Abbeville" },
      { "city": "Alexandria" },
      { "city": "Bastrop" },
      { "city": "Baton Rouge" },
      { "city": "Bogalusa" },
      { "city": "Bossier City" },
      { "city": "Gretna" },
      { "city": "Houma" },
      { "city": "Lafayette" },
      { "city": "Lake Charles" },
      { "city": "Monroe" },
      { "city": "Morgan City" },
      { "city": "Natchitoches" },
      { "city": "New Iberia" },
      { "city": "New Orleans" },
      { "city": "Opelousas" },
      { "city": "Ruston" },
      { "city": "Saint Martinville" },
      { "city": "Shreveport" },
      { "city": "Thibodaux" },
      { "city": "Maine" },

    ]
  },
  {
    "stateId": 19, "state": "Maine", "cities": [
      { "city": "      Auburn" },
      { "city": "Augusta" },
      { "city": "Bangor" },
      { "city": "Bar Harbor" },
      { "city": "Bath" },
      { "city": "Belfast" },
      { "city": "Biddeford" },
      { "city": "Boothbay Harbor" },
      { "city": "Brunswick" },
      { "city": "Calais" },
      { "city": "Caribou" },
      { "city": "Castine" },
      { "city": "Eastport" },
      { "city": "Ellsworth" },
      { "city": "Farmington" },
      { "city": "Fort Kent" },
      { "city": "Gardiner" },
      { "city": "Houlton" },
      { "city": "Kennebunkport" },
      { "city": "Kittery" },
      { "city": "Lewiston" },
      { "city": "Lubec" },
      { "city": "Machias" },
      { "city": "Orono" },
      { "city": "Portland" },
      { "city": "Presque Isle" },
      { "city": "Rockland" },
      { "city": "Rumford" },
      { "city": "Saco" },
      { "city": "Scarborough" },
      { "city": "Waterville" },
      { "city": "York" },
    ]
  },
  {
    "stateId": 20, "state": "Maryland", "cities": [
      { "city": "Aberdeen" },
      { "city": "Annapolis" },
      { "city": "Baltimore" },
      { "city": "Bethesda-Chevy Chase" },
      { "city": "Bowie" },
      { "city": "Cambridge" },
      { "city": "Catonsville" },
      { "city": "College Park" },
      { "city": "Columbia" },
      { "city": "Cumberland" },
      { "city": "Easton" },
      { "city": "Elkton" },
      { "city": "Emmitsburg" },
      { "city": "Frederick" },
      { "city": "Greenbelt" },
      { "city": "Hagerstown" },
      { "city": "Hyattsville" },
      { "city": "Laurel" },
      { "city": "Oakland" },
      { "city": "Ocean City" },
      { "city": "Rockville" },
      { "city": "Saint Marys City" },
      { "city": "Salisbury" },
      { "city": "Silver Spring" },
      { "city": "Takoma Park" },
      { "city": "Towson" },
      { "city": "Westminster" },
    ]
  },
  {
    "stateId": 21, "state": "Massachusetts", "cities": [
      { "city": "Abington" },
      { "city": "Adams" },
      { "city": "Amesbury" },
      { "city": "Amherst" },
      { "city": "Andover" },
      { "city": "Arlington" },
      { "city": "Athol" },
      { "city": "Attleboro" },
      { "city": "Barnstable" },
      { "city": "Bedford" },
      { "city": "Beverly" },
      { "city": "Boston" },
      { "city": "Bourne" },
      { "city": "Braintree" },
      { "city": "Brockton" },
      { "city": "Brookline" },
      { "city": "Cambridge" },
      { "city": "Canton" },
      { "city": "Charlestown" },
      { "city": "Chelmsford" },
      { "city": "Chelsea" },
      { "city": "Chicopee" },
      { "city": "Clinton" },
      { "city": "Cohasset" },
      { "city": "Concord" },
      { "city": "Danvers" },
      { "city": "Dartmouth" },
      { "city": "Dedham" },
      { "city": "Dennis" },
      { "city": "Duxbury" },
      { "city": "Eastham" },
      { "city": "Edgartown" },
      { "city": "Everett" },
      { "city": "Fairhaven" },
      { "city": "Fall River" },
      { "city": "Falmouth" },
      { "city": "Fitchburg" },
      { "city": "Framingham" },
      { "city": "Gloucester" },
      { "city": "Great Barrington" },
      { "city": "Greenfield" },
      { "city": "Groton" },
      { "city": "Harwich" },
      { "city": "Haverhill" },
      { "city": "Hingham" },
      { "city": "Holyoke" },
      { "city": "Hyannis" },
      { "city": "Ipswich" },
      { "city": "Lawrence" },
      { "city": "Lenox" },
      { "city": "Leominster" },
      { "city": "Lexington" },
      { "city": "Lowell" },
      { "city": "Ludlow" },
      { "city": "Lynn" },
      { "city": "Malden" },
      { "city": "Marblehead" },
      { "city": "Marlborough" },
      { "city": "Medford" },
      { "city": "Milton" },
      { "city": "Nahant" },
      { "city": "Natick" },
      { "city": "New Bedford" },
      { "city": "Newburyport" },
      { "city": "Newton" },
      { "city": "North Adams" },
      { "city": "Northampton" },
      { "city": "Norton" },
      { "city": "Norwood" },
      { "city": "Peabody" },
      { "city": "Pittsfield" },
      { "city": "Plymouth" },
      { "city": "Provincetown" },
      { "city": "Quincy" },
      { "city": "Randolph" },
      { "city": "Revere" },
      { "city": "Salem" },
      { "city": "Sandwich" },
      { "city": "Saugus" },
      { "city": "Somerville" },
      { "city": "South Hadley" },
      { "city": "Springfield" },
      { "city": "Stockbridge" },
      { "city": "Stoughton" },
      { "city": "Sturbridge" },
      { "city": "Sudbury" },
      { "city": "Taunton" },
      { "city": "Tewksbury" },
      { "city": "Truro" },
      { "city": "Watertown" },
      { "city": "Webster" },
      { "city": "Wellesley" },
      { "city": "Wellfleet" },
      { "city": "West Bridgewater" },
      { "city": "West Springfield" },
      { "city": "Westfield" },
      { "city": "Weymouth" },
      { "city": "Whitman" },
      { "city": "Williamstown" },
      { "city": "Woburn" },
      { "city": "Woods Hole" },
      { "city": "Worcester" },
    ]
  },
  {
    "stateId": 22, "state": "Michigan", "cities": [
      { "city": "Adrian" },
      { "city": "Alma" },
      { "city": "Ann Arbor" },
      { "city": "Battle Creek" },
      { "city": "Bay City" },
      { "city": "Benton Harbor" },
      { "city": "Bloomfield Hills" },
      { "city": "Cadillac" },
      { "city": "Charlevoix" },
      { "city": "Cheboygan" },
      { "city": "Dearborn" },
      { "city": "Detroit" },
      { "city": "East Lansing" },
      { "city": "Eastpointe" },
      { "city": "Ecorse" },
      { "city": "Escanaba" },
      { "city": "Flint" },
      { "city": "Grand Haven" },
      { "city": "Grand Rapids" },
      { "city": "Grayling" },
      { "city": "Grosse Pointe" },
      { "city": "Hancock" },
      { "city": "Highland Park" },
      { "city": "Holland" },
      { "city": "Houghton" },
      { "city": "Interlochen" },
      { "city": "Iron Mountain" },
      { "city": "Ironwood" },
      { "city": "Ishpeming" },
      { "city": "Jackson" },
      { "city": "Kalamazoo" },
      { "city": "Lansing" },
      { "city": "Livonia" },
      { "city": "Ludington" },
      { "city": "Mackinaw City" },
      { "city": "Manistee" },
      { "city": "Marquette" },
      { "city": "Menominee" },
      { "city": "Midland" },
      { "city": "Monroe" },
      { "city": "Mount Clemens" },
      { "city": "Mount Pleasant" },
      { "city": "Muskegon" },
      { "city": "Niles" },
      { "city": "Petoskey" },
      { "city": "Pontiac" },
      { "city": "Port Huron" },
      { "city": "Royal Oak" },
      { "city": "Saginaw" },
      { "city": "Saint Ignace" },
      { "city": "Saint Joseph" },
      { "city": "Sault Sainte Marie" },
      { "city": "Traverse City" },
      { "city": "Trenton" },
      { "city": "Warren" },
      { "city": "Wyandotte" },
      { "city": "Ypsilanti" }
    ]
  },
  {
    "stateId": 23, "state": "Minnesota", "cities": [
      { "city": "Albert Lea" },
      { "city": "Alexandria" },
      { "city": "Austin" },
      { "city": "Bemidji" },
      { "city": "Bloomington" },
      { "city": "Brainerd" },
      { "city": "Crookston" },
      { "city": "Duluth" },
      { "city": "Ely" },
      { "city": "Eveleth" },
      { "city": "Faribault" },
      { "city": "Fergus Falls" },
      { "city": "Hastings" },
      { "city": "Hibbing" },
      { "city": "International Falls" },
      { "city": "Little Falls" },
      { "city": "Mankato" },
      { "city": "Minneapolis" },
      { "city": "Moorhead" },
      { "city": "New Ulm" },
      { "city": "Northfield" },
      { "city": "Owatonna" },
      { "city": "Pipestone" },
      { "city": "Red Wing" },
      { "city": "Rochester" },
      { "city": "Saint Cloud" },
      { "city": "Saint Paul" },
      { "city": "Sauk Centre" },
      { "city": "South Saint Paul" },
      { "city": "Stillwater" },
      { "city": "Virginia" },
      { "city": "Willmar" },
      { "city": "Winona" },
    ]
  },
  {
    "stateId": 24, "state": "Mississippi", "cities": [
      { "city": "Bay Saint Louis" },
      { "city": "Biloxi" },
      { "city": "Canton" },
      { "city": "Clarksdale" },
      { "city": "Columbia" },
      { "city": "Columbus" },
      { "city": "Corinth" },
      { "city": "Greenville" },
      { "city": "Greenwood" },
      { "city": "Grenada" },
      { "city": "Gulfport" },
      { "city": "Hattiesburg" },
      { "city": "Holly Springs" },
      { "city": "Jackson" },
      { "city": "Laurel" },
      { "city": "Meridian" },
      { "city": "Natchez" },
      { "city": "Ocean Springs" },
      { "city": "Oxford" },
      { "city": "Pascagoula" },
      { "city": "Pass Christian" },
      { "city": "Philadelphia" },
      { "city": "Port Gibson" },
      { "city": "Starkville" },
      { "city": "Tupelo" },
      { "city": "Vicksburg" },
      { "city": "West Point" },
      { "city": "Yazoo City" }
    ]
  },
  {
    "stateId": 25, "state": "Missouri", "cities": [
      { "city": "Boonville" },
      { "city": "Branson" },
      { "city": "Cape Girardeau" },
      { "city": "Carthage" },
      { "city": "Chillicothe" },
      { "city": "Clayton" },
      { "city": "Columbia" },
      { "city": "Excelsior Springs" },
      { "city": "Ferguson" },
      { "city": "Florissant" },
      { "city": "Fulton" },
      { "city": "Hannibal" },
      { "city": "Independence" },
      { "city": "Jefferson City" },
      { "city": "Joplin" },
      { "city": "Kansas City" },
      { "city": "Kirksville" },
      { "city": "Lamar" },
      { "city": "Lebanon" },
      { "city": "Lexington" },
      { "city": "Maryville" },
      { "city": "Mexico" },
      { "city": "Monett" },
      { "city": "Neosho" },
      { "city": "New Madrid" },
      { "city": "Rolla" },
      { "city": "Saint Charles" },
      { "city": "Saint Joseph" },
      { "city": "Saint Louis" },
      { "city": "Sainte Genevieve" },
      { "city": "Salem" },
      { "city": "Sedalia" },
      { "city": "Springfield" },
      { "city": "Warrensburg" },
      { "city": "West Plains" },
    ]
  },
  {
    "stateId": 26, "state": "Montana", "cities": [
      { "city": "Anaconda" },
      { "city": "Billings" },
      { "city": "Bozeman" },
      { "city": "Butte" },
      { "city": "Dillon" },
      { "city": "Fort Benton" },
      { "city": "Glendive" },
      { "city": "Great Falls" },
      { "city": "Havre" },
      { "city": "Helena" },
      { "city": "Kalispell" },
      { "city": "Lewistown" },
      { "city": "Livingston" },
      { "city": "Miles City" },
      { "city": "Missoula" },
      { "city": "Virginia City" },
    ]
  },
  {
    "stateId": 26, "state": "Nebraska", "cities": [
      { "city": "Beatrice" },
      { "city": "Bellevue" },
      { "city": "Boys Town" },
      { "city": "Chadron" },
      { "city": "Columbus" },
      { "city": "Fremont" },
      { "city": "Grand Island" },
      { "city": "Hastings" },
      { "city": "Kearney" },
      { "city": "Lincoln" },
      { "city": "McCook" },
      { "city": "Minden" },
      { "city": "Nebraska City" },
      { "city": "Norfolk" },
      { "city": "North Platte" },
      { "city": "Omaha" },
      { "city": "Plattsmouth" },
      { "city": "Red Cloud" },
      { "city": "Sidney" },
    ]
  },
  {
    "stateId": 27, "state": "Nevada", "cities": [
      { "city": "Boulder City" },
      { "city": "Carson City" },
      { "city": "Elko" },
      { "city": "Ely" },
      { "city": "Fallon" },
      { "city": "Genoa" },
      { "city": "Goldfield" },
      { "city": "Henderson" },
      { "city": "Las Vegas" },
      { "city": "North Las Vegas" },
      { "city": "Reno" },
      { "city": "Sparks" },
      { "city": "Virginia City" },
      { "city": "Winnemucca" },
    ]
  },
  {
    "stateId": 28, "state": "New Hampshire", "cities": [
      { "city": "Berlin" },
      { "city": "Claremont" },
      { "city": "Concord" },
      { "city": "Derry" },
      { "city": "Dover" },
      { "city": "Durham" },
      { "city": "Exeter" },
      { "city": "Franklin" },
      { "city": "Hanover" },
      { "city": "Hillsborough" },
      { "city": "Keene" },
      { "city": "Laconia" },
      { "city": "Lebanon" },
      { "city": "Manchester" },
      { "city": "Nashua" },
      { "city": "Peterborough" },
      { "city": "Plymouth" },
      { "city": "Portsmouth" },
      { "city": "Rochester" },
      { "city": "Salem" },
      { "city": "Somersworth" },
    ]
  },
  {
    "stateId": 29, "state": "New Jersey", "cities": [
      { "city": "Asbury Park" },
      { "city": "Atlantic City" },
      { "city": "Bayonne" },
      { "city": "Bloomfield" },
      { "city": "Bordentown" },
      { "city": "Bound Brook" },
      { "city": "Bridgeton" },
      { "city": "Burlington" },
      { "city": "Caldwell" },
      { "city": "Camden" },
      { "city": "Cape May" },
      { "city": "Clifton" },
      { "city": "Cranford" },
      { "city": "East Orange" },
      { "city": "Edison" },
      { "city": "Elizabeth" },
      { "city": "Englewood" },
      { "city": "Fort Lee" },
      { "city": "Glassboro" },
      { "city": "Hackensack" },
      { "city": "Haddonfield" },
      { "city": "Hoboken" },
      { "city": "Irvington" },
      { "city": "Jersey City" },
      { "city": "Lakehurst" },
      { "city": "Lakewood" },
      { "city": "Long Beach" },
      { "city": "Long Branch" },
      { "city": "Madison" },
      { "city": "Menlo Park" },
      { "city": "Millburn" },
      { "city": "Millville" },
      { "city": "Montclair" },
      { "city": "Morristown" },
      { "city": "Mount Holly" },
      { "city": "New Brunswick" },
      { "city": "New Milford" },
      { "city": "Newark" },
      { "city": "Ocean City" },
      { "city": "Orange" },
      { "city": "Parsippany–Troy Hills" },
      { "city": "Passaic" },
      { "city": "Paterson" },
      { "city": "Perth Amboy" },
      { "city": "Plainfield" },
      { "city": "Princeton" },
      { "city": "Ridgewood" },
      { "city": "Roselle" },
      { "city": "Rutherford" },
      { "city": "Salem" },
      { "city": "Somerville" },
      { "city": "South Orange Village" },
      { "city": "Totowa" },
      { "city": "Trenton" },
      { "city": "Union" },
      { "city": "Union City" },
      { "city": "Vineland" },
      { "city": "Wayne" },
      { "city": "Weehawken" },
      { "city": "West New York" },
      { "city": "West Orange" },
      { "city": "Willingboro" },
      { "city": "Woodbridge" },
    ]
  },
  {
    "stateId": 30, "state": "New Mexico", "cities": [
      { "city": "Acoma" },
      { "city": "Alamogordo" },
      { "city": "Albuquerque" },
      { "city": "Artesia" },
      { "city": "Belen" },
      { "city": "Carlsbad" },
      { "city": "Clovis" },
      { "city": "Deming" },
      { "city": "Farmington" },
      { "city": "Gallup" },
      { "city": "Grants" },
      { "city": "Hobbs" },
      { "city": "Las Cruces" },
      { "city": "Las Vegas" },
      { "city": "Los Alamos" },
      { "city": "Lovington" },
      { "city": "Portales" },
      { "city": "Raton" },
      { "city": "Roswell" },
      { "city": "Santa Fe" },
      { "city": "Shiprock" },
      { "city": "Silver City" },
      { "city": "Socorro" },
      { "city": "Taos" },
      { "city": "Truth or Consequences" },
      { "city": "Tucumcari" },
    ]
  },
  {
    "stateId": 30, "state": "New York", "cities": [
      { "city": "Albany" },
      { "city": "Amsterdam" },
      { "city": "Auburn" },
      { "city": "Babylon" },
      { "city": "Batavia" },
      { "city": "Beacon" },
      { "city": "Bedford" },
      { "city": "Binghamton" },
      { "city": "Bronx" },
      { "city": "Brooklyn" },
      { "city": "Buffalo" },
      { "city": "Chautauqua" },
      { "city": "Cheektowaga" },
      { "city": "Clinton" },
      { "city": "Cohoes" },
      { "city": "Coney Island" },
      { "city": "Cooperstown" },
      { "city": "Corning" },
      { "city": "Cortland" },
      { "city": "Crown Point" },
      { "city": "Dunkirk" },
      { "city": "East Aurora" },
      { "city": "East Hampton" },
      { "city": "Eastchester" },
      { "city": "Elmira" },
      { "city": "Flushing" },
      { "city": "Forest Hills" },
      { "city": "Fredonia" },
      { "city": "Garden City" },
      { "city": "Geneva" },
      { "city": "Glens Falls" },
      { "city": "Gloversville" },
      { "city": "Great Neck" },
      { "city": "Hammondsport" },
      { "city": "Harlem" },
      { "city": "Hempstead" },
      { "city": "Herkimer" },
      { "city": "Hudson" },
      { "city": "Huntington" },
      { "city": "Hyde Park" },
      { "city": "Ilion" },
      { "city": "Ithaca" },
      { "city": "Jamestown" },
      { "city": "Johnstown" },
      { "city": "Kingston" },
      { "city": "Lackawanna" },
      { "city": "Lake Placid" },
      { "city": "Levittown" },
      { "city": "Lockport" },
      { "city": "Mamaroneck" },
      { "city": "Manhattan" },
      { "city": "Massena" },
      { "city": "Middletown" },
      { "city": "Mineola" },
      { "city": "Mount Vernon" },
      { "city": "New Paltz" },
      { "city": "New Rochelle" },
      { "city": "New Windsor" },
      { "city": "New York City" },
      { "city": "Newburgh" },
      { "city": "Niagara Falls" },
      { "city": "North Hempstead" },
      { "city": "Nyack" },
      { "city": "Ogdensburg" },
      { "city": "Olean" },
      { "city": "Oneida" },
      { "city": "Oneonta" },
      { "city": "Ossining" },
      { "city": "Oswego" },
      { "city": "Oyster Bay" },
      { "city": "Palmyra" },
      { "city": "Peekskill" },
      { "city": "Plattsburgh" },
      { "city": "Port Washington" },
      { "city": "Potsdam" },
      { "city": "Poughkeepsie" },
      { "city": "Queens" },
      { "city": "Rensselaer" },
      { "city": "Rochester" },
      { "city": "Rome" },
      { "city": "Rotterdam" },
      { "city": "Rye" },
      { "city": "Sag Harbor" },
      { "city": "Saranac Lake" },
      { "city": "Saratoga Springs" },
      { "city": "Scarsdale" },
      { "city": "Schenectady" },
      { "city": "Seneca Falls" },
      { "city": "Southampton" },
      { "city": "Staten Island" },
      { "city": "Stony Brook" },
      { "city": "Stony Point" },
      { "city": "Syracuse" },
      { "city": "Tarrytown" },
      { "city": "Ticonderoga" },
      { "city": "Tonawanda" },
      { "city": "Troy" },
      { "city": "Utica" },
      { "city": "Watertown" },
      { "city": "Watervliet" },
      { "city": "Watkins Glen" },
      { "city": "West Seneca" },
      { "city": "White Plains" },
      { "city": "Woodstock" },
      { "city": "Yonkers" },
    ]
  },
  {
    "stateId": 30, "state": "North Carolina", "cities": [
      { "city": "Asheboro" },
      { "city": "Asheville" },
      { "city": "Bath" },
      { "city": "Beaufort" },
      { "city": "Boone" },
      { "city": "Burlington" },
      { "city": "Chapel Hill" },
      { "city": "Charlotte" },
      { "city": "Concord" },
      { "city": "Durham" },
      { "city": "Edenton" },
      { "city": "Elizabeth City" },
      { "city": "Fayetteville" },
      { "city": "Gastonia" },
      { "city": "Goldsboro" },
      { "city": "Greensboro" },
      { "city": "Greenville" },
      { "city": "Halifax" },
      { "city": "Henderson" },
      { "city": "Hickory" },
      { "city": "High Point" },
      { "city": "Hillsborough" },
      { "city": "Jacksonville" },
      { "city": "Kinston" },
      { "city": "Kitty Hawk" },
      { "city": "Lumberton" },
      { "city": "Morehead City" },
      { "city": "Morganton" },
      { "city": "Nags Head" },
      { "city": "New Bern" },
      { "city": "Pinehurst" },
      { "city": "Raleigh" },
      { "city": "Rocky Mount" },
      { "city": "Salisbury" },
      { "city": "Shelby" },
      { "city": "Washington" },
      { "city": "Wilmington" },
      { "city": "Wilson" },
      { "city": "Winston-Salem" }
    ]
  },
  {
    "stateId": 31, "state": "North Dakota", "cities": [
      { "city": "Bismarck" },
      { "city": "Devils Lake" },
      { "city": "Dickinson" },
      { "city": "Fargo" },
      { "city": "Grand Forks" },
      { "city": "Jamestown" },
      { "city": "Mandan" },
      { "city": "Minot" },
      { "city": "Rugby" },
      { "city": "Valley City" },
      { "city": "Wahpeton" },
      { "city": "Williston" },
    ]
  },
  {
    "stateId": 32, "state": "Ohio", "cities": [
      { "city": "Akron" },
      { "city": "Alliance" },
      { "city": "Ashtabula" },
      { "city": "Athens" },
      { "city": "Barberton" },
      { "city": "Bedford" },
      { "city": "Bellefontaine" },
      { "city": "Bowling Green" },
      { "city": "Canton" },
      { "city": "Chillicothe" },
      { "city": "Cincinnati" },
      { "city": "Cleveland" },
      { "city": "Cleveland Heights" },
      { "city": "Columbus" },
      { "city": "Conneaut" },
      { "city": "Cuyahoga Falls" },
      { "city": "Dayton" },
      { "city": "Defiance" },
      { "city": "Delaware" },
      { "city": "East Cleveland" },
      { "city": "East Liverpool" },
      { "city": "Elyria" },
      { "city": "Euclid" },
      { "city": "Findlay" },
      { "city": "Gallipolis" },
      { "city": "Greenville" },
      { "city": "Hamilton" },
      { "city": "Kent" },
      { "city": "Kettering" },
      { "city": "Lakewood" },
      { "city": "Lancaster" },
      { "city": "Lima" },
      { "city": "Lorain" },
      { "city": "Mansfield" },
      { "city": "Marietta" },
      { "city": "Marion" },
      { "city": "Martins Ferry" },
      { "city": "Massillon" },
      { "city": "Mentor" },
      { "city": "Middletown" },
      { "city": "Milan" },
      { "city": "Mount Vernon" },
      { "city": "New Philadelphia" },
      { "city": "Newark" },
      { "city": "Niles" },
      { "city": "North College Hill" },
      { "city": "Norwalk" },
      { "city": "Oberlin" },
      { "city": "Painesville" },
      { "city": "Parma" },
      { "city": "Piqua" },
      { "city": "Portsmouth" },
      { "city": "Put-in-Bay" },
      { "city": "Salem" },
      { "city": "Sandusky" },
      { "city": "Shaker Heights" },
      { "city": "Springfield" },
      { "city": "Steubenville" },
      { "city": "Tiffin" },
      { "city": "Toledo" },
      { "city": "Urbana" },
      { "city": "Warren" },
      { "city": "Wooster" },
      { "city": "Worthington" },
      { "city": "Xenia" },
      { "city": "Yellow Springs" },
      { "city": "Youngstown" },
      { "city": "Zanesville" },
    ]
  },
  {
    "stateId": 33, "state": "Oklahoma", "cities": [
      { "city": "Ada" },
      { "city": "Altus" },
      { "city": "Alva" },
      { "city": "Anadarko" },
      { "city": "Ardmore" },
      { "city": "Bartlesville" },
      { "city": "Bethany" },
      { "city": "Chickasha" },
      { "city": "Claremore" },
      { "city": "Clinton" },
      { "city": "Cushing" },
      { "city": "Duncan" },
      { "city": "Durant" },
      { "city": "Edmond" },
      { "city": "El Reno" },
      { "city": "Elk City" },
      { "city": "Enid" },
      { "city": "Eufaula" },
      { "city": "Frederick" },
      { "city": "Guthrie" },
      { "city": "Guymon" },
      { "city": "Hobart" },
      { "city": "Holdenville" },
      { "city": "Hugo" },
      { "city": "Lawton" },
      { "city": "McAlester" },
      { "city": "Miami" },
      { "city": "Midwest City" },
      { "city": "Moore" },
      { "city": "Muskogee" },
      { "city": "Norman" },
      { "city": "Oklahoma City" },
      { "city": "Okmulgee" },
      { "city": "Pauls Valley" },
      { "city": "Pawhuska" },
      { "city": "Perry" },
      { "city": "Ponca City" },
      { "city": "Pryor" },
      { "city": "Sallisaw" },
      { "city": "Sand Springs" },
      { "city": "Sapulpa" },
      { "city": "Seminole" },
      { "city": "Shawnee" },
      { "city": "Stillwater" },
      { "city": "Tahlequah" },
      { "city": "The Village" },
      { "city": "Tulsa" },
      { "city": "Vinita" },
      { "city": "Wewoka" },
      { "city": "Woodward" },
    ]
  },
  {
    "stateId": 34, "state": "Oregon", "cities": [
      { "city": "Albany" },
      { "city": "Ashland" },
      { "city": "Astoria" },
      { "city": "Baker City" },
      { "city": "Beaverton" },
      { "city": "Bend" },
      { "city": "Brookings" },
      { "city": "Burns" },
      { "city": "Coos Bay" },
      { "city": "Corvallis" },
      { "city": "Eugene" },
      { "city": "Grants Pass" },
      { "city": "Hillsboro" },
      { "city": "Hood River" },
      { "city": "Jacksonville" },
      { "city": "John Day" },
      { "city": "Klamath Falls" },
      { "city": "La Grande" },
      { "city": "Lake Oswego" },
      { "city": "Lakeview" },
      { "city": "McMinnville" },
      { "city": "Medford" },
      { "city": "Newberg" },
      { "city": "Newport" },
      { "city": "Ontario" },
      { "city": "Oregon City" },
      { "city": "Pendleton" },
      { "city": "Port Orford" },
      { "city": "Portland" },
      { "city": "Prineville" },
      { "city": "Redmond" },
      { "city": "Reedsport" },
      { "city": "Roseburg" },
      { "city": "Salem" },
      { "city": "Seaside" },
      { "city": "Springfield" },
      { "city": "The Dalles" },
      { "city": "Tillamook" },
    ]
  },
  {
    "stateId": 35, "state": "Pennsylvania", "cities": [
      { "city": "Abington" },
      { "city": "Aliquippa" },
      { "city": "Allentown" },
      { "city": "Altoona" },
      { "city": "Ambridge" },
      { "city": "Bedford" },
      { "city": "Bethlehem" },
      { "city": "Bloomsburg" },
      { "city": "Bradford" },
      { "city": "Bristol" },
      { "city": "Carbondale" },
      { "city": "Carlisle" },
      { "city": "Chambersburg" },
      { "city": "Chester" },
      { "city": "Columbia" },
      { "city": "Easton" },
      { "city": "Erie" },
      { "city": "Franklin" },
      { "city": "Germantown" },
      { "city": "Gettysburg" },
      { "city": "Greensburg" },
      { "city": "Hanover" },
      { "city": "Harmony" },
      { "city": "Harrisburg" },
      { "city": "Hazleton" },
      { "city": "Hershey" },
      { "city": "Homestead" },
      { "city": "Honesdale" },
      { "city": "Indiana" },
      { "city": "Jeannette" },
      { "city": "Jim Thorpe" },
      { "city": "Johnstown" },
      { "city": "Lancaster" },
      { "city": "Lebanon" },
      { "city": "Levittown" },
      { "city": "Lewistown" },
      { "city": "Lock Haven" },
      { "city": "Lower Southampton" },
      { "city": "McKeesport" },
      { "city": "Meadville" },
      { "city": "Middletown" },
      { "city": "Monroeville" },
      { "city": "Nanticoke" },
      { "city": "New Castle" },
      { "city": "New Hope" },
      { "city": "New Kensington" },
      { "city": "Norristown" },
      { "city": "Oil City" },
      { "city": "Philadelphia" },
      { "city": "Phoenixville" },
      { "city": "Pittsburgh" },
      { "city": "Pottstown" },
      { "city": "Pottsville" },
      { "city": "Reading" },
      { "city": "Scranton" },
      { "city": "Shamokin" },
      { "city": "Sharon" },
      { "city": "State College" },
      { "city": "Stroudsburg" },
      { "city": "Sunbury" },
      { "city": "Swarthmore" },
      { "city": "Tamaqua" },
      { "city": "Titusville" },
      { "city": "Uniontown" },
      { "city": "Warren" },
      { "city": "Washington" },
      { "city": "West Chester" },
      { "city": "Wilkes-Barre" },
      { "city": "Williamsport" },
      { "city": "York" },
    ]
  },
  {
    "stateId": 36, "state": "Rhode Island", "cities": [
      { "city": "Barrington" },
      { "city": "Bristol" },
      { "city": "Central Falls" },
      { "city": "Cranston" },
      { "city": "East Greenwich" },
      { "city": "East Providence" },
      { "city": "Kingston" },
      { "city": "Middletown" },
      { "city": "Narragansett" },
      { "city": "Newport" },
      { "city": "North Kingstown" },
      { "city": "Pawtucket" },
      { "city": "Portsmouth" },
      { "city": "Providence" },
      { "city": "South Kingstown" },
      { "city": "Tiverton" },
      { "city": "Warren" },
      { "city": "Warwick" },
      { "city": "Westerly" },
      { "city": "Wickford" },
      { "city": "Woonsocket" },
    ]
  },
  {
    "stateId": 37, "state": "South Carolina", "cities": [
      { "city": "Abbeville" },
      { "city": "Aiken" },
      { "city": "Anderson" },
      { "city": "Beaufort" },
      { "city": "Camden" },
      { "city": "Charleston" },
      { "city": "Columbia" },
      { "city": "Darlington" },
      { "city": "Florence" },
      { "city": "Gaffney" },
      { "city": "Georgetown" },
      { "city": "Greenville" },
      { "city": "Greenwood" },
      { "city": "Hartsville" },
      { "city": "Lancaster" },
      { "city": "Mount Pleasant" },
      { "city": "Myrtle Beach" },
      { "city": "Orangeburg" },
      { "city": "Rock Hill" },
      { "city": "Spartanburg" },
      { "city": "Sumter" },
      { "city": "Union" },
    ]
  },
  {
    "stateId": 38, "state": "South Dakota", "cities": [
      { "city": "Aberdeen" },
      { "city": "Belle Fourche" },
      { "city": "Brookings" },
      { "city": "Canton" },
      { "city": "Custer" },
      { "city": "De Smet" },
      { "city": "Deadwood" },
      { "city": "Hot Springs" },
      { "city": "Huron" },
      { "city": "Lead" },
      { "city": "Madison" },
      { "city": "Milbank" },
      { "city": "Mitchell" },
      { "city": "Mobridge" },
      { "city": "Pierre" },
      { "city": "Rapid City" },
      { "city": "Sioux Falls" },
      { "city": "Spearfish" },
      { "city": "Sturgis" },
      { "city": "Vermillion" },
      { "city": "Watertown" },
      { "city": "Yankton" },
    ]
  },
  {
    "stateId": 39, "state": "Tennessee", "cities": [
      { "city": "Alcoa" },
      { "city": "Athens" },
      { "city": "Chattanooga" },
      { "city": "Clarksville" },
      { "city": "Cleveland" },
      { "city": "Columbia" },
      { "city": "Cookeville" },
      { "city": "Dayton" },
      { "city": "Elizabethton" },
      { "city": "Franklin" },
      { "city": "Gallatin" },
      { "city": "Gatlinburg" },
      { "city": "Greeneville" },
      { "city": "Jackson" },
      { "city": "Johnson City" },
      { "city": "Jonesborough" },
      { "city": "Kingsport" },
      { "city": "Knoxville" },
      { "city": "Lebanon" },
      { "city": "Maryville" },
      { "city": "Memphis" },
      { "city": "Morristown" },
      { "city": "Murfreesboro" },
      { "city": "Nashville" },
      { "city": "Norris" },
      { "city": "Oak Ridge" },
      { "city": "Shelbyville" },
      { "city": "Tullahoma" },
    ]
  },
  {
    "stateId": 40, "state": "Texas", "cities": [
      { "city": "Abilene" },
      { "city": "Alpine" },
      { "city": "Amarillo" },
      { "city": "Arlington" },
      { "city": "Austin" },
      { "city": "Baytown" },
      { "city": "Beaumont" },
      { "city": "Big Spring" },
      { "city": "Borger" },
      { "city": "Brownsville" },
      { "city": "Bryan" },
      { "city": "Canyon" },
      { "city": "Cleburne" },
      { "city": "College Station" },
      { "city": "Corpus Christi" },
      { "city": "Crystal City" },
      { "city": "Dallas" },
      { "city": "Del Rio" },
      { "city": "Denison" },
      { "city": "Denton" },
      { "city": "Eagle Pass" },
      { "city": "Edinburg" },
      { "city": "El Paso" },
      { "city": "Fort Worth" },
      { "city": "Freeport" },
      { "city": "Galveston" },
      { "city": "Garland" },
      { "city": "Goliad" },
      { "city": "Greenville" },
      { "city": "Harlingen" },
      { "city": "Houston" },
      { "city": "Huntsville" },
      { "city": "Irving" },
      { "city": "Johnson City" },
      { "city": "Kilgore" },
      { "city": "Killeen" },
      { "city": "Kingsville" },
      { "city": "Laredo" },
      { "city": "Longview" },
      { "city": "Lubbock" },
      { "city": "Lufkin" },
      { "city": "Marshall" },
      { "city": "McAllen" },
      { "city": "McKinney" },
      { "city": "Mesquite" },
      { "city": "Midland" },
      { "city": "Mission" },
      { "city": "Nacogdoches" },
      { "city": "New Braunfels" },
      { "city": "Odessa" },
      { "city": "Orange" },
      { "city": "Pampa" },
      { "city": "Paris" },
      { "city": "Pasadena" },
      { "city": "Pecos" },
      { "city": "Pharr" },
      { "city": "Plainview" },
      { "city": "Plano" },
      { "city": "Port Arthur" },
      { "city": "Port Lavaca" },
      { "city": "Richardson" },
      { "city": "San Angelo" },
      { "city": "San Antonio" },
      { "city": "San Felipe" },
      { "city": "San Marcos" },
      { "city": "Sherman" },
      { "city": "Sweetwater" },
      { "city": "Temple" },
      { "city": "Texarkana" },
      { "city": "Texas City" },
      { "city": "Tyler" },
      { "city": "Uvalde" },
      { "city": "Victoria" },
      { "city": "Waco" },
      { "city": "Weatherford" },
      { "city": "Wichita Falls" },
      { "city": "Ysleta" },
    ]
  },
  {
    "stateId": 41, "state": "Utah", "cities": [
      { "city": "Alta" },
      { "city": "American Fork" },
      { "city": "Bountiful" },
      { "city": "Brigham City" },
      { "city": "Cedar City" },
      { "city": "Clearfield" },
      { "city": "Delta" },
      { "city": "Fillmore" },
      { "city": "Green River" },
      { "city": "Heber City" },
      { "city": "Kanab" },
      { "city": "Layton" },
      { "city": "Lehi" },
      { "city": "Logan" },
      { "city": "Manti" },
      { "city": "Moab" },
      { "city": "Monticello" },
      { "city": "Murray" },
      { "city": "Nephi" },
      { "city": "Ogden" },
      { "city": "Orderville" },
      { "city": "Orem" },
      { "city": "Panguitch" },
      { "city": "Park City" },
      { "city": "Payson" },
      { "city": "Price" },
      { "city": "Provo" },
      { "city": "Saint George" },
      { "city": "Salt Lake City" },
      { "city": "Spanish Fork" },
      { "city": "Springville" },
      { "city": "Tooele" },
      { "city": "Vernal" },
    ]
  },
  {
    "stateId": 42, "state": "Vermont", "cities": [
      { "city": "Barre" },
      { "city": "Bellows Falls" },
      { "city": "Bennington" },
      { "city": "Brattleboro" },
      { "city": "Burlington" },
      { "city": "Essex" },
      { "city": "Manchester" },
      { "city": "Middlebury" },
      { "city": "Montpelier" },
      { "city": "Newport" },
      { "city": "Plymouth" },
      { "city": "Rutland" },
      { "city": "Saint Albans" },
      { "city": "Saint Johnsbury" },
      { "city": "Sharon" },
      { "city": "Winooski" },
    ]
  },
  {
    "stateId": 43, "state": "Virginia", "cities": [
      { "city": "Abingdon" },
      { "city": "Alexandria" },
      { "city": "Bristol" },
      { "city": "Charlottesville" },
      { "city": "Chesapeake" },
      { "city": "Danville" },
      { "city": "Fairfax" },
      { "city": "Falls Church" },
      { "city": "Fredericksburg" },
      { "city": "Hampton" },
      { "city": "Hanover" },
      { "city": "Hopewell" },
      { "city": "Lexington" },
      { "city": "Lynchburg" },
      { "city": "Manassas" },
      { "city": "Martinsville" },
      { "city": "New Market" },
      { "city": "Newport News" },
      { "city": "Norfolk" },
      { "city": "Petersburg" },
      { "city": "Portsmouth" },
      { "city": "Reston" },
      { "city": "Richmond" },
      { "city": "Roanoke" },
      { "city": "Staunton" },
      { "city": "Suffolk" },
      { "city": "Virginia Beach" },
      { "city": "Waynesboro" },
      { "city": "Williamsburg" },
      { "city": "Winchester" },
    ]
  },
  {
    "stateId": 44, "state": "Washington", "cities": [
      { "city": "Aberdeen" },
      { "city": "Anacortes" },
      { "city": "Auburn" },
      { "city": "Bellevue" },
      { "city": "Bellingham" },
      { "city": "Bremerton" },
      { "city": "Centralia" },
      { "city": "Coulee Dam" },
      { "city": "Coupeville" },
      { "city": "Ellensburg" },
      { "city": "Ephrata" },
      { "city": "Everett" },
      { "city": "Hoquiam" },
      { "city": "Kelso" },
      { "city": "Kennewick" },
      { "city": "Longview" },
      { "city": "Moses Lake" },
      { "city": "Oak Harbor" },
      { "city": "Olympia" },
      { "city": "Pasco" },
      { "city": "Point Roberts" },
      { "city": "Port Angeles" },
      { "city": "Pullman" },
      { "city": "Puyallup" },
      { "city": "Redmond" },
      { "city": "Renton" },
      { "city": "Richland" },
      { "city": "Seattle" },
      { "city": "Spokane" },
      { "city": "Tacoma" },
      { "city": "Vancouver" },
      { "city": "Walla Walla" },
      { "city": "Wenatchee" },
      { "city": "Yakima" },
    ]
  },
  {
    "stateId": 45, "state": "West Virginia", "cities": [
      { "city": "Bath" },
      { "city": "Beckley" },
      { "city": "Bluefield" },
      { "city": "Buckhannon" },
      { "city": "Charles Town" },
      { "city": "Charleston" },
      { "city": "Clarksburg" },
      { "city": "Elkins" },
      { "city": "Fairmont" },
      { "city": "Grafton" },
      { "city": "Harpers Ferry" },
      { "city": "Hillsboro" },
      { "city": "Hinton" },
      { "city": "Huntington" },
      { "city": "Keyser" },
      { "city": "Lewisburg" },
      { "city": "Logan" },
      { "city": "Martinsburg" },
      { "city": "Morgantown" },
      { "city": "Moundsville" },
      { "city": "New Martinsville" },
      { "city": "Parkersburg" },
      { "city": "Philippi" },
      { "city": "Point Pleasant" },
      { "city": "Princeton" },
      { "city": "Romney" },
      { "city": "Shepherdstown" },
      { "city": "South Charleston" },
      { "city": "Summersville" },
      { "city": "Weirton" },
      { "city": "Welch" },
      { "city": "Wellsburg" },
      { "city": "Weston" },
      { "city": "Wheeling" },
      { "city": "White Sulphur Springs" },
      { "city": "Williamson" },
    ]
  },
  {
    "stateId": 46, "state": "Wisconsin", "cities": [
      { "city": "Appleton" },
      { "city": "Ashland" },
      { "city": "Baraboo" },
      { "city": "Belmont" },
      { "city": "Beloit" },
      { "city": "Eau Claire" },
      { "city": "Fond du Lac" },
      { "city": "Green Bay" },
      { "city": "Hayward" },
      { "city": "Janesville" },
      { "city": "Kenosha" },
      { "city": "La Crosse" },
      { "city": "Lake Geneva" },
      { "city": "Madison" },
      { "city": "Manitowoc" },
      { "city": "Marinette" },
      { "city": "Menasha" },
      { "city": "Milwaukee" },
      { "city": "Neenah" },
      { "city": "New Glarus" },
      { "city": "Oconto" },
      { "city": "Oshkosh" },
      { "city": "Peshtigo" },
      { "city": "Portage" },
      { "city": "Prairie du Chien" },
      { "city": "Racine" },
      { "city": "Rhinelander" },
      { "city": "Ripon" },
      { "city": "Sheboygan" },
      { "city": "Spring Green" },
      { "city": "Stevens Point" },
      { "city": "Sturgeon Bay" },
      { "city": "Superior" },
      { "city": "Waukesha" },
      { "city": "Wausau" },
      { "city": "Wauwatosa" },
      { "city": "West Allis" },
      { "city": "West Bend" },
      { "city": "Wisconsin Dells" },
    ]
  },
  {
    "stateId": 47, "state": "Wyoming", "cities": [
      { "city": "Buffalo" },
      { "city": "Casper" },
      { "city": "Cheyenne" },
      { "city": "Cody" },
      { "city": "Douglas" },
      { "city": "Evanston" },
      { "city": "Gillette" },
      { "city": "Green River" },
      { "city": "Jackson" },
      { "city": "Lander" },
      { "city": "Laramie" },
      { "city": "Newcastle" },
      { "city": "Powell" },
      { "city": "Rawlins" },
      { "city": "Riverton" },
      { "city": "Rock Springs" },
      { "city": "Sheridan" },
      { "city": "Ten Sleep" },
      { "city": "Thermopolis" },
      { "city": "Torrington" },
      { "city": "Worland" }
    ]
  }
]

